### PR TITLE
Deploy Protocol Contracts to new chains

### PR DESCRIPTION
**Pull request by Ashar2shahid**
The protocol contracts have been deployed to the following chains:

linea:
[AccessControlRegistry](https://lineascan.build/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
[AirnodeRrpV0](https://lineascan.build/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
[AirnodeRrpV0DryRun](https://lineascan.build/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
[RequesterAuthorizerWithAirnode](https://lineascan.build/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

linea-goerli-testnet:
[AccessControlRegistry](https://goerli.lineascan.build/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
[AirnodeRrpV0](https://goerli.lineascan.build/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
[AirnodeRrpV0DryRun](https://goerli.lineascan.build/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
[RequesterAuthorizerWithAirnode](https://goerli.lineascan.build/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

mantle:
[AccessControlRegistry](https://explorer.mantle.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1/contracts?contract-tab=code#address-tabs)
[AirnodeRrpV0](https://explorer.mantle.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd/contracts?contract-tab=code#address-tabs)
[AirnodeRrpV0DryRun](https://explorer.mantle.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f/contracts?contract-tab=code#address-tabs)
[RequesterAuthorizerWithAirnode](https://explorer.mantle.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178/contracts?contract-tab=code#address-tabs)

mantle-goerli-testnet:
[AccessControlRegistry](https://explorer.testnet.mantle.xyz/address/0xD223DfDCb888CA1539bb3459a83c543A1608F038/contracts?contract-tab=code#address-tabs)
[AirnodeRrpV0](https://explorer.testnet.mantle.xyz/address/0x20C9e9610d4e719a39F82893b3f42e2730F42778/contracts?contract-tab=code#address-tabs)
[AirnodeRrpV0DryRun](https://explorer.testnet.mantle.xyz/address/0x3e10e6eF3c602885a9Cafd9785BD2143c52fbFF1/contracts?contract-tab=code#address-tabs)
[RequesterAuthorizerWithAirnode](https://explorer.testnet.mantle.xyz/address/0x4A0b644219d07fEa25B701AAf89b963576b468dC/contracts?contract-tab=code#address-tabs)

base:
[AccessControlRegistry](https://basescan.org/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
[AirnodeRrpV0](https://basescan.org/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
[AirnodeRrpV0DryRun](https://basescan.org/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
[RequesterAuthorizerWithAirnode](https://basescan.org/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

base-goerli-testnet:
[AccessControlRegistry](https://goerli.basescan.org/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
[AirnodeRrpV0](https://goerli.basescan.org/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
[AirnodeRrpV0DryRun](https://goerli.basescan.org/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
[RequesterAuthorizerWithAirnode](https://goerli.basescan.org/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

polygon-zkevm:
[AccessControlRegistry](https://zkevm.polygonscan.com/address/0x92e5125adf385d86bedb950793526106143b6df1#code)
[AirnodeRrpV0](https://zkevm.polygonscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
[AirnodeRrpV0DryRun](https://zkevm.polygonscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
[RequesterAuthorizerWithAirnode](https://zkevm.polygonscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

polygon-zkevm-testnet(block explorer is currently broken):
[AccessControlRegistry](https://testnet-zkevm.polygonscan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1)
[AirnodeRrpV0](https://testnet-zkevm.polygonscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd)
[AirnodeRrpV0DryRun](https://testnet-zkevm.polygonscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f)
[RequesterAuthorizerWithAirnode](https://testnet-zkevm.polygonscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178)

This cannot be merged until https://github.com/api3dao/chains/pull/64 is merged

### CODE REVIEW

**Comment by Ashar2shahid** [comment]
@andreogle can you take a look at https://github.com/api3dao/chains/pull/64 so I can then make this ready for review ?

**Comment by andreogle** [comment]
fyi, ChainAPI has received a request to support Polygon zkEVM (mainnet and testnet). Once this PR is merged, the above networks will also be added to ChainAPI

**Review by dcroote — COMMENTED** [review]
@Ashar2shahid - shouldn't the "Verify Protocol Deployments" CI workflow have run here given all of the new `packages/airnode-protocol` paths?

**Review by dcroote — APPROVED** [review]
Looks good, one minor question: mantle deployments are deterministic but mantle-goerli-testnet aren't?

**Comment by Ashar2shahid** [comment]
@dcroote mantle-testnet desterminstic deployments were failing because I suspect the factory isn't deployed there: https://explorer.testnet.mantle.xyz/address/0x4e59b44847b379578588920cA78FbF26c0B4956C/transactions#address-tabs . When hardhat attempts to deploy it, I kept getting this error:

```
sending eth to create2 contract deployer address (0x3fab184622dc19b6109349b94811493bf2a45362) (tx: 0xeb71a5d76e5b4295e79c2bb9da530758905b43b99a8a2fe828e0974728c9424c)...
deploying create2 deployer contract (at 0x4e59b44847b379578588920ca78fbf26c0b4956c) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy)An unexpected error occurred:

Error: ERROR processing /Users/ashar/Desktop/API3/Ubuntu/airnode/packages/airnode-protocol/deploy/1_deploy.js:
ProviderError: gas price too high: 100000000000 wei, use at most tx.gasPrice = 1 wei
    at HttpProvider.request (/Users/ashar/Desktop/API3/Ubuntu/airnode/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
```
I tried with minimal gas price but it kept failing

**Comment by dcroote** [comment]
Not sure what the issue is with the create2 deployer contract at 0x4e59b44847b379578588920ca78fbf26c0b4956c, but it's absence looks like the issue. Transient gas issues? Otherwise, while it's not ideal, this wouldn't be the first chain with nondeterministic deployments and we now have functionality where these addresses don't need to be manually specified in the config as of v0.12 so it's even less of an issue.

**Pull request merged**
