### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by aquarat**
This bumps package versions for Airnode to v0.8.

We may have to add a changeset if we wish to satisfy the CI (pre-push check failed).

I see there were two minor commits after this branch was created. This branch is based on the same commit hash used to build the packages Martin tested.

Relates to #1421

### CODE REVIEW

**Comment by amarthadan** [comment]
> We may have to add a changeset if we wish to satisfy the CI (pre-push check failed).

:thinking: Didn't think about that tbh. But it is kinda ridiculous to add the changeset to these PRs. I'll figure something out. Force it for now (without a changeset).

**Comment by Siegrift** [comment]
> Didn't think about that tbh. But it is kinda ridiculous to add the changeset to these PRs. I'll figure something out. Force it for now (without a changeset).

Why not just add an empty changeset?

**Comment by aquarat** [comment]
I force-pushed a fresh branch, this time with `new-version` to bump the examples, etc. and I also added an empty changeset. I updated the guide and followed it exactly and this was the result (except for the force-push part 😉).

As soon as this is reviewed I'll publish the packages @amarthadan

**Comment by aquarat** [comment]
I see one of the tests failed 🔬

**Comment by Siegrift** [comment]
> I see one of the tests failed 🔬

That is the same failure that appears in https://github.com/api3dao/airnode/pull/1424. The problem seems to be in how the CI installs dependencies, since it seems it ignores the yarn.lock file and tries to install the latest OIS. This will of course trigger an error in validator.

@amarthadan or @aquarat Will you have time to look at this? (I'd volunteer, but I am having a doctor appointment in a few hours).

**Comment by aquarat** [comment]
Hey, thanks for that, I'm working on this and I identified the issue. I'm currently running tests locally with pinned versions of ois instead of `^`.

Good luck with your appointment 💪

**Comment by aquarat** [comment]
Might be time to move the links check to the master branch.

**Review by amarthadan — APPROVED** [review]
I don't really like the strict pin much but it should be fine for now :+1:

**Comment by dcroote** [comment]
Apologies for the reassignments- there were two "Release v0.8.0" on the board- now it's just the issue #1421

**Pull request merged**
