### PR TITLE
Fix deployer CLI example

### PR DESCRIPTION
**Pull request by Siegrift**
Fixes minor inconsistency introduced in the deployer refactor.

### CODE REVIEW

**Review by amarthadan — APPROVED** [review]
Sorry, I didn't catch that :man_facepalming:

**Comment by dcroote** [comment]
I think then 2 pages each for `v0.9` and `v0.10` of the docs will need updating too:
- https://docs.api3.org/airnode/v0.9/grp-providers/docker/deployer-image.html#remove-with-deployment-details
- https://docs.api3.org/airnode/v0.9/reference/packages/deployer.html#remove-with-deployment-details

**Comment by amarthadan** [comment]
Wait, that won't work actually. You now have to provide the full address not just the short version.

**Comment by amarthadan** [comment]
> I think then 2 pages each for `v0.9` and `v0.10` of the docs will need updating too:
> 
>     * https://docs.api3.org/airnode/v0.9/grp-providers/docker/deployer-image.html#remove-with-deployment-details
> 
>     * https://docs.api3.org/airnode/v0.9/reference/packages/deployer.html#remove-with-deployment-details

Yes, I will update the docs as well, I just didn't get to it yet.

**Comment by Siegrift** [comment]
> Wait, that won't work actually. You now have to provide the full address not just the short version.

🤦 Sorry, bad morning for me.

**Pull request merged**
