### PR TITLE
Deploy on Sepolia

### PR DESCRIPTION
**Pull request by bbenligiray**
I couldn't deploy deterministically because hardhat-deploy doesn't seem to support Sepolia yet (unlike xdeployer). I may redeploy once that becomes available (but maybe not?). I verified the contracts on Etherscan.

Btw, TS complains about the types in [this bit](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/scripts/generate-references.ts#L38-L43). What do?

### CODE REVIEW

**Review by Siegrift — APPROVED** [review]
👍 LGTM.

Looked at the verified contracts on Sepolia etherscan and it LGTM. I plan to test the RRP request when implementing https://github.com/api3dao/airnode/issues/1280 as the ultimate test...

Btw. do we need this document? https://api3dao.atlassian.net/wiki/spaces/AIRNODE/pages/154697729/Airnode+protocol+deployment+process (There was a task for this some time ago, but I am not sure we need it).

**Comment by bbenligiray** [comment]
@Siegrift Let me review that document before merging this. Btw, did you read the second part of the PR post?

**Comment by Siegrift** [comment]
> Btw, did you read the second part of the PR post?

Which second part do you mean?

**Comment by bbenligiray** [comment]
> Btw, TS complains about the types in [this bit](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/scripts/generate-references.ts#L38-L43). What do?

**Comment by bbenligiray** [comment]
Thanks, will check it out

**Pull request merged**
