### PR TITLE
Bump @api3/ois to 1.1.2 and bump zod

### LINKED ISSUE #1422: airnode-validator fails to build with the newly published @api3/ois package
## Description

airnode-validator fails to build with the newly published @api3/ois package.

## Version

Please provide your Node.js, Yarn and relevant Airnode versions. Are you building from a branch, which commit?
Node 14.19.3
Yarn 1.22.19
master branch with ois dependency bumped (5acdba4f88ffeb219fdd47d615c2c85ab725825e with patch included below applied)

## Present Behaviour

airnode-validator fails to build with the newly published @api3/ois package.

## Expected Behaviour

The build should succeed.

## Steps to reproduce

Bump @api3/ois dependency to the latest in packages in Airnode that use it and then attempt the build.

## Additional comments:
It probably relates to @api3dao/ois issue 

The build log:
```
In airnode, commit 5acdba4f88ffeb219fdd47d615c2c85ab725825e:
yarn bootstrap
yarn build
...
yarn run v1.22.19
$ lerna run build --stream && ts-node scripts/make-cli-executable.ts
lerna notice cli v5.5.0
lerna info Executing command in 10 packages: "yarn run build"
@api3/airnode-abi: $ yarn run clean && yarn run compile
@api3/airnode-adapter: $ yarn run clean && yarn run compile
@api3/airnode-validator: $ yarn run clean && yarn run compile
@api3/airnode-protocol: $ yarn run clean && yarn compile
@api3/airnode-abi: $ rimraf -rf *.tsbuildinfo ./dist ./build *.tgz
@api3/airnode-protocol: $ rimraf -rf ./src/contracts *.tsbuildinfo ./dist ./build *.tgz
@api3/airnode-validator: $ rimraf -rf *.tsbuildinfo ./dist ./build *.tgz
@api3/airnode-adapter: $ rimraf -rf *.tsbuildinfo ./dist ./build *.tgz
@api3/airnode-abi: $ tsc --build tsconfig.json
@api3/airnode-protocol: $ yarn run compile:contracts && yarn run compile:tsc
@api3/airnode-validator: $ yarn tsc --build tsconfig.json
@api3/airnode-adapter: $ hardhat compile && tsc --build tsconfig.json
@api3/airnode-protocol: $ hardhat compile
@api3/airnode-validator: $ /Users/aquarat/Projects/airnode/node_modules/.bin/tsc --build tsconfig.json
@api3/airnode-protocol: Nothing to compile
@api3/airnode-protocol: $ yarn compile:contract-dts && yarn compile:copy-contract-dts && tsc --build tsconfig.json
@api3/airnode-protocol: $ yarn typechain --target ethers-v5 --out-dir ./src/contracts "./artifacts/contracts/**/!(*.dbg).json"
@api3/airnode-protocol: $ /Users/aquarat/Projects/airnode/node_modules/.bin/typechain --target ethers-v5 --out-dir ./src/contracts './artifacts/contracts/**/!(*.dbg).json'
@api3/airnode-adapter: Nothing to compile
@api3/airnode-protocol: Successfully generated 113 typings!
@api3/airnode-protocol: $ copyfiles -u 1 "src/contracts/**/*.d.ts" dist/src
@api3/airnode-validator: src/config/config.ts(425,10): error TS2589: Type instantiation is excessively deep and possibly infinite.
@api3/airnode-validator: src/config/config.ts(425,10): error TS2589: Type instantiation is excessively deep and possibly infinite.
@api3/airnode-validator: src/config/config.ts(425,10): error TS2589: Type instantiation is excessively deep and possibly infinite.
@api3/airnode-validator: error Command failed with exit code 1.
@api3/airnode-validator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@api3/airnode-validator: error Command failed with exit code 1.
@api3/airnode-validator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@api3/airnode-validator: error Command failed with exit code 1.
@api3/airnode-validator: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@api3/airnode-validator'
error Command failed with exit code 1.
```

Patch:
```
diff --git a/packages/airnode-adapter/package.json b/packages/airnode-adapter/package.json
index 34ec0a22..7f6005fe 100644
--- a/packages/airnode-adapter/package.json
+++ b/packages/airnode-adapter/package.json
@@ -19,7 +19,7 @@
     "test:watch": "yarn test:ts --watch"
   },
   "dependencies": {
-    "@api3/ois": "^1.1.1",
+    "@api3/ois": "^1.1.2",
     "@api3/promise-utils": "^0.3.0",
     "axios": "^0.27.2",
     "bignumber.js": "^9.1.0",
diff --git a/packages/airnode-node/package.json b/packages/airnode-node/package.json
index 68439ecb..350712b7 100644
--- a/packages/airnode-node/package.json
+++ b/packages/airnode-node/package.json
@@ -29,7 +29,7 @@
     "@api3/airnode-protocol": "^0.7.1",
     "@api3/airnode-utilities": "^0.7.1",
     "@api3/airnode-validator": "^0.7.1",
-    "@api3/ois": "^1.1.1",
+    "@api3/ois": "^1.1.2",
     "@api3/promise-utils": "^0.3.0",
     "aws-sdk": "^2.1209.0",
     "body-parser": "^1.20.0",
diff --git a/packages/airnode-validator/package.json b/packages/airnode-validator/package.json
index f41ea11e..88834027 100644
--- a/packages/airnode-validator/package.json
+++ b/packages/airnode-validator/package.json
@@ -23,7 +23,7 @@
     "test:e2e:update-snapshot": "yarn test:e2e --updateSnapshot"
   },
   "dependencies": {
-    "@api3/ois": "^1.1.1",
+    "@api3/ois": "^1.1.2",
     "@api3/promise-utils": "^0.3.0",
     "dotenv": "^16.0.2",
     "ethers": "^5.7.0",
diff --git a/yarn.lock b/yarn.lock
index d36759bf..98d9642d 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -10,13 +10,13 @@
     "@jridgewell/gen-mapping" "^0.1.0"
     "@jridgewell/trace-mapping" "^0.3.9"
 
-"@api3/ois@^1.1.1":
-  version "1.1.1"
-  resolved "https://registry.yarnpkg.com/@api3/ois/-/ois-1.1.1.tgz#8760c3d4d35435d68a4726ac9d4d17e91e0ac02e"
-  integrity sha512-u7LPVmcstVdgNXnZ0JgWV23NA4SPnT8Uk5PkguFnmMr1Or1J7TO4Iq2lpTJnzJcwUTy52MndCfEMVvGvHJ5Pww==
+"@api3/ois@^1.1.2":
+  version "1.1.2"
+  resolved "https://registry.yarnpkg.com/@api3/ois/-/ois-1.1.2.tgz#104dbbe38c864868fa99a7c979230ba992651ee3"
+  integrity sha512-kKF/GtmVewrdhKd/mnAX/UCGs508dcqP/Np/FG7B8I3fX6LAH1Gg3SGXiIQZFQ0V9u8CStsf7CpZj9BVLLri+Q==
   dependencies:
     lodash "^4.17.21"
-    zod "^3.17.3"
+    zod "^3.18.0"
 
 "@api3/promise-utils@^0.3.0":
   version "0.3.0"
@@ -7472,7 +7472,6 @@ ethereumjs-abi@0.6.8, ethereumjs-abi@^0.6.8:
 
 "ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git":
   version "0.6.8"
-  uid ee3994657fa7a427238e6ba92a84d0b529bbcde0
   resolved "git+https://github.com/ethereumjs/ethereumjs-abi.git#ee3994657fa7a427238e6ba92a84d0b529bbcde0"
   dependencies:
     bn.js "^4.11.8"
@@ -17260,3 +17259,8 @@ zod@^3.17.3:
   version "3.18.0"
   resolved "https://registry.yarnpkg.com/zod/-/zod-3.18.0.tgz#2eed58b3cafb8d9a67aa2fee69279702f584f3bc"
   integrity sha512-gwTm8RfUCe8l9rDwN5r2A17DkAa8Ez4Yl4yXqc5VqeGaXaJahzYYXbTwvhroZi0SNBqTwh/bKm2N0mpCzuw4bA==
+
+zod@^3.18.0:
+  version "3.19.0"
+  resolved "https://registry.yarnpkg.com/zod/-/zod-3.19.0.tgz#a9303fcaed0950a3dc57bf35cc11f6282d4f52f2"
+  integrity sha512-Yw0qvUsCNGBe5YacikdMt5gVYeUuaEFVDIHKMfElrGSaBhwR3CQK6vOzgfAJOjTdGIhEeoaj8GtT+NDZrepZbw==
```

### LINKED ISSUE #1430: Manually bump OIS in Airnode
## Description

Airnode's CI flow currently doesn't use frozen lock files. This means that even patch releases of OIS get installed and this breaks airnode-examples (eg. '1.1.1' won't match the current version of '1.1.2').

To resolve this with minimal fuss for the v0.8.0 Airnode release the ois version was pinned to '1.1.1' (instead of '^1.1.1').

The package will need to be manually updated in future, paying special attention to the airnode-examples.

There may be a slicker alternative to the above, feel free to suggest something or raise it on Slack.

Also refer to https://github.com/api3dao/airnode/pull/1428

### PR DESCRIPTION
**Pull request by dcroote**
Closes #1422. Closes #1430. 

Zod version bump is necessary for @api3/ois@1.1.2 compatibility ([see my issue comment here](https://github.com/api3dao/airnode/issues/1422#issuecomment-1238900265)).

### CODE REVIEW

**Comment by aquarat** [comment]
Thanks @dcroote :) 
I assume we'll keep this for Airnode v0.8.1 as this isn't critical and Martin is currently testing the v0.8.0 packages. LMK if you disagree.

**Comment by Siegrift** [comment]
I'd say we can leave this for 0.9. The fix is OIS is could be considered as a feature (implement a check that was not there before) rather than a bug. I don't think we need to release new patch for this.

**Comment by dcroote** [comment]
I agree with @Siegrift that this can be left for 0.9.

**Review by Siegrift — APPROVED** [review]
👍 LGTM

**Pull request merged**
