### PR TITLE
AN-364: Further changes to override HardHat automatic solidity compiler download

### PR DESCRIPTION
**Pull request by aquarat**
The compiler downloaded now is JS based, which means it is architecture and OS-agnostic.

I insert a function into HardHat's TASK subsystem so as to force both the compiler type and path.
The platform is no longer detected and used to inform compiler selection.
The reasons for this are:
- Sometimes HardHat switches from `linux-amd64` as a platform to `wasm`
- The `linux-amd64` solidity binary doesn't run on the node docker image downloaded due to a missing library dependency.

While I was at it I swapped hardhat.conf.js for .ts in airnode-protocol.

I'll ask @bbenligiray to test this as his build was still failing after the last _fix_.

### CODE REVIEW

**Comment by aquarat** [comment]
In response to Burak's comments I'm working on a cleaner alternative.

**Comment by bbenligiray** [comment]
@aquarat Let me know if I need to test. Also, prefer creating the branches in this repo instead of your own.

**Comment by aquarat** [comment]
> @aquarat Let me know if I need to test. Also, prefer creating the branches in this repo instead of your own.

Sorry for the delay. It had crossed my mind @ branches in parent rather than personal, thanks for confirming.
I'm just trying something potentially cleaner as an alternative - I'll keep you updated.

**Comment by aquarat** [comment]
Closing in favour of [a different approach](https://github.com/api3dao/airnode/pull/698).

**Pull request closed without merging**
