### PR TITLE
Deploy RRP contracts to new market chains

### PR DESCRIPTION
**Pull request by vanshwassan**
Deployed RRP contracts to the new chains that recently got added to the Market. Deterministic deployment worked for all the chains.

- Astar
  [AccessControlRegistry](https://astar-zkevm.explorer.startale.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://astar-zkevm.explorer.startale.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://astar-zkevm.explorer.startale.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://astar-zkevm.explorer.startale.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Astar Sepolia Testnet
  [AccessControlRegistry](https://zkyoto.explorer.startale.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://zkyoto.explorer.startale.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://zkyoto.explorer.startale.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://zkyoto.explorer.startale.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Bob
  [AccessControlRegistry](https://explorer.gobob.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.gobob.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.gobob.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.gobob.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Bob Sepolia Testnet
  [AccessControlRegistry](https://testnet-explorer.gobob.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1?tab=contract)
  [AirnodeRrpV0](https://testnet-explorer.gobob.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?tab=contract)
  [AirnodeRrpV0DryRun](https://testnet-explorer.gobob.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?tab=contract)
  [RequesterAuthorizerWithAirnode](https://testnet-explorer.gobob.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?tab=contract)

- Bsquared
  [AccessControlRegistry](https://explorer.bsquared.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.bsquared.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.bsquared.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.bsquared.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Bsquared Testnet
  [AccessControlRegistry](https://testnet-explorer.bsquared.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://testnet-explorer.bsquared.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://testnet-explorer.bsquared.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://testnet-explorer.bsquared.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Core
  [AccessControlRegistry](https://scan.coredao.org/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://scan.coredao.org/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://scan.coredao.org/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://scan.coredao.org/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Core Testnet
  [AccessControlRegistry](https://scan.test.btcs.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://scan.test.btcs.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://scan.test.btcs.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://scan.test.btcs.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Fraxtal
  [AccessControlRegistry](https://fraxscan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://fraxscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://fraxscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://fraxscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Fraxtal Holesky Testnet
  [AccessControlRegistry](https://holesky.fraxscan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://holesky.fraxscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://holesky.fraxscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://holesky.fraxscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Inevm
  [AccessControlRegistry](https://inevm.calderaexplorer.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://inevm.calderaexplorer.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://inevm.calderaexplorer.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://inevm.calderaexplorer.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Inevm Testnet
  [AccessControlRegistry](https://inevm-testnet.explorer.caldera.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1?tab=contract)
  [AirnodeRrpV0](https://inevm-testnet.explorer.caldera.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?tab=contract)
  [AirnodeRrpV0DryRun](https://inevm-testnet.explorer.caldera.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?tab=contract)
  [RequesterAuthorizerWithAirnode](https://inevm-testnet.explorer.caldera.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?tab=contract)

- Kava
  [AccessControlRegistry](http://kavascan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1?t=code)
  [AirnodeRrpV0](http://kavascan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?t=code)
  [AirnodeRrpV0DryRun](http://kavascan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?t=code)
  [RequesterAuthorizerWithAirnode](http://kavascan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?t=code)

- Kava Testnet (Block explorer causing some issues, not able to verify contracts)
  [AccessControlRegistry](https://testnet.kavascan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1)
  [AirnodeRrpV0](https://testnet.kavascan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd)
  [AirnodeRrpV0DryRun](https://testnet.kavascan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f)
  [RequesterAuthorizerWithAirnode](https://testnet.kavascan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178)

- Kroma
  [AccessControlRegistry](https://kromascan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://kromascan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://kromascan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://kromascan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Kroma Sepolia Testnet
  [AccessControlRegistry](https://sepolia.kromascan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://sepolia.kromascan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://sepolia.kromascan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://sepolia.kromascan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Linea Sepolia Testnet
  [AccessControlRegistry](https://sepolia.lineascan.build/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://sepolia.lineascan.build/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://sepolia.lineascan.build/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://sepolia.lineascan.build/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Lukso
  [AccessControlRegistry](https://explorer.execution.mainnet.lukso.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.execution.mainnet.lukso.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.execution.mainnet.lukso.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.execution.mainnet.lukso.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Lukso Testnet
  [AccessControlRegistry](https://explorer.execution.testnet.lukso.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.execution.testnet.lukso.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.execution.testnet.lukso.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.execution.testnet.lukso.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Mantle Sepolia Testnet
  [AccessControlRegistry](https://explorer.sepolia.mantle.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.sepolia.mantle.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.sepolia.mantle.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.sepolia.mantle.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Merlin
  [AccessControlRegistry](https://scan.merlinchain.io/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://scan.merlinchain.io/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://scan.merlinchain.io/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://scan.merlinchain.io/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Merlin Testnet
  [AccessControlRegistry](https://testnet-scan.merlinchain.io/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://testnet-scan.merlinchain.io/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://testnet-scan.merlinchain.io/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://testnet-scan.merlinchain.io/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Mode
  [AccessControlRegistry](https://explorer.mode.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://explorer.mode.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://explorer.mode.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://explorer.mode.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Mode Sepolia Testnet
  [AccessControlRegistry](https://sepolia.explorer.mode.network/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://sepolia.explorer.mode.network/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://sepolia.explorer.mode.network/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://sepolia.explorer.mode.network/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- opBNB
  [AccessControlRegistry](https://opbnbscan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1?tab=Contract&p=1)
  [AirnodeRrpV0](https://opbnbscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?tab=Contract&p=1)
  [AirnodeRrpV0DryRun](https://opbnbscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?tab=Contract&p=1)
  [RequesterAuthorizerWithAirnode](https://opbnbscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?tab=Contract&p=1)

- opBNB Testnet
  [AccessControlRegistry](https://testnet.opbnbscan.com/address/0x92E5125adF385d86beDb950793526106143b6Df1?tab=Contract&p=1)
  [AirnodeRrpV0](https://testnet.opbnbscan.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?tab=Contract&p=1)
  [AirnodeRrpV0DryRun](https://testnet.opbnbscan.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?tab=Contract&p=1)
  [RequesterAuthorizerWithAirnode](https://testnet.opbnbscan.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?tab=Contract&p=1)

- Rari
  [AccessControlRegistry](https://mainnet.explorer.rarichain.org/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://mainnet.explorer.rarichain.org/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://mainnet.explorer.rarichain.org/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://mainnet.explorer.rarichain.org/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Rari Arbitrum Sepolia Testnet
  [AccessControlRegistry](https://testnet.explorer.rarichain.org/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://testnet.explorer.rarichain.org/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://testnet.explorer.rarichain.org/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://testnet.explorer.rarichain.org/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Sei
  [AccessControlRegistry](https://seitrace.com/address/0x92E5125adF385d86beDb950793526106143b6Df1?chain=pacific-1&tab=contract)
  [AirnodeRrpV0](https://seitrace.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?chain=pacific-1&tab=contract)
  [AirnodeRrpV0DryRun](https://seitrace.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?chain=pacific-1&tab=contract)
  [RequesterAuthorizerWithAirnode](https://seitrace.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?chain=pacific-1&tab=contract)

- Sei Testnet
  [AccessControlRegistry](https://seitrace.com/address/0x92E5125adF385d86beDb950793526106143b6Df1?chain=arctic-1&tab=contract)
  [AirnodeRrpV0](https://seitrace.com/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?chain=arctic-1&tab=contract)
  [AirnodeRrpV0DryRun](https://seitrace.com/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?chain=arctic-1&tab=contract)
  [RequesterAuthorizerWithAirnode](https://seitrace.com/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?chain=arctic-1&tab=contract)

- Taiko
  [AccessControlRegistry](https://taikoscan.io/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://taikoscan.io/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://taikoscan.io/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://taikoscan.io/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Taiko Holesky Testnet
  [AccessControlRegistry](https://blockscoutapi.hekla.taiko.xyz/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  [AirnodeRrpV0](https://blockscoutapi.hekla.taiko.xyz/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  [AirnodeRrpV0DryRun](https://blockscoutapi.hekla.taiko.xyz/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  [RequesterAuthorizerWithAirnode](https://blockscoutapi.hekla.taiko.xyz/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- X Layer
  [AccessControlRegistry](https://www.oklink.com/xlayer/address/0x92e5125adf385d86bedb950793526106143b6df1/contract)
  [AirnodeRrpV0](https://www.oklink.com/xlayer/address/0xa0ad79d995ddeeb18a14eaef56a549a04e3aa1bd/contract)
  [AirnodeRrpV0DryRun](https://www.oklink.com/xlayer/address/0x2e768206bf5112e7d7efaf1d9df614c26475193f/contract)
  [RequesterAuthorizerWithAirnode](https://www.oklink.com/xlayer/address/0xf18c105d0375e80980e4eed829a4a68a539e6178/contract)

- X Layer Sepolia Testnet
  [AccessControlRegistry](https://www.oklink.com/xlayer-test/address/0x92e5125adf385d86bedb950793526106143b6df1/contract)
  [AirnodeRrpV0](https://www.oklink.com/xlayer-test/address/0xa0ad79d995ddeeb18a14eaef56a549a04e3aa1bd/contract)
  [AirnodeRrpV0DryRun](https://www.oklink.com/xlayer-test/address/0x2e768206bf5112e7d7efaf1d9df614c26475193f/contract)
  [RequesterAuthorizerWithAirnode](https://www.oklink.com/xlayer-test/address/0xf18c105d0375e80980e4eed829a4a68a539e6178/contract)

### CODE REVIEW

**Review by dcroote — COMMENTED** [review]
Any thoughts on why `x-layer` and `x-layer-sepolia-testnet` [fail](https://github.com/api3dao/airnode/actions/runs/9440032331/job/26052582814) verification?

**Comment by vanshwassan** [comment]
> Any thoughts on why `x-layer` and `x-layer-sepolia-testnet` [fail](https://github.com/api3dao/airnode/actions/runs/9440032331/job/26052582814) verification?

It's probably because the `transactionHash` and `receipt` are missing from the json files generated after the deployment. I remember this happening when I deployed the protocol contracts on [`arbitrum-sepolia`](https://github.com/api3dao/airnode/pull/1974#issuecomment-2029837088) in the past too. Will try to look into it but for now, I will just generate and add the fields manually.

**Comment by Ashar2shahid** [comment]
I reran the [tests](https://github.com/api3dao/airnode/actions/runs/9487145981/job/26148530357) all the new chains are passing tests, Ill update api3/chains to change the providers for the old chains that keep failing CI, (gnosis/polygon/ethereum-sepolia)

**Review by dcroote — APPROVED** [review]
> I reran the [tests](https://github.com/api3dao/airnode/actions/runs/9487145981/job/26148530357) all the new chains are passing tests, Ill update api3/chains to change the providers for the old chains that keep failing CI, (gnosis/polygon/ethereum-sepolia)

Nice, makes sense

**Review by Ashar2shahid — APPROVED** [review]

**Pull request merged**
