### PR TITLE
Bump api3/ois to v2.3.2

### PR DESCRIPTION
**Pull request by dcroote**
Needed for Airnode v0.14.1 patch release, [see here](https://github.com/api3dao/ois/pull/130#issue-2116339122). My plan is into merge to master, cherry-pick this commit on the `v0.14` branch, then release. Sound like a plan?

### CODE REVIEW

**Comment by Siegrift** [comment]
> Sound like a plan?

Yeah, although I don't see the need to rush it. It shouldn't be blocking any feature.

**Review by Siegrift — APPROVED** [review]
👍 LGTM

**Comment by dcroote** [comment]
> Yeah, although I don't see the need to rush it. It shouldn't be blocking any feature.

Agreed, and I believe @Ashar2shahid mentioned the possibility of another PR related to increasing memory

**Comment by Siegrift** [comment]
> and I believe @Ashar2shahid mentioned the possibility of another PR related to increasing memory

Mhh, I think I missed/forget this. Can you give me more context.

**Comment by dcroote** [comment]
@Ashar2shahid said never mind so we're good

**Pull request merged**
