### PR TITLE
Replace deprecated Goerli testnets

### PR DESCRIPTION
**Pull request by vanshwassan**
Some of the testnets based on Goerli are now officially deprecated. Some of them also caused the CI runs to fail. Removed the following Goerli testnets:
- [Arbitrum Goerli Testnet](https://testnet.arbiscan.io/) / [source](https://docs.arbitrum.io/for-devs/concepts/public-chains#arbitrum-goerli)
- [Optimism Goerli Testnet](https://goerli-optimism.etherscan.io/) / [source](https://blog.oplabs.co/op-sepolia/)
- [Base Goerli Testnet](https://goerli.basescan.org/) / [source](https://www.alchemy.com/blog/base-goerli-testnet-deprecation)
- [Metis Goerli Testnet](https://goerli-explorer.metis.io/) / [source - removed from docs](https://docs.metis.io/dev/readme/connection-details)

Also deployed protocol contracts to the newer Sepolia Testnets:
- Arbitrum Sepolia Testnet
  - [AccessControlRegistry](https://sepolia.arbiscan.io/address/0x92E5125adF385d86beDb950793526106143b6Df1#code)
  - [AirnodeRrpV0](https://sepolia.arbiscan.io/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd#code)
  - [AirnodeRrpV0DryRun](https://sepolia.arbiscan.io/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f#code)
  - [RequesterAuthorizerWithAirnode](https://sepolia.arbiscan.io/address/0xf18c105D0375E80980e4EED829a4A68A539E6178#code)

- Metis Sepolia Testnet
  - [AccessControlRegistry](https://sepolia-explorer.metisdevops.link/address/0x92E5125adF385d86beDb950793526106143b6Df1?tab=contract)
  - [AirnodeRrpV0](https://sepolia-explorer.metisdevops.link/address/0xa0AD79D995DdeeB18a14eAef56A549A04e3Aa1Bd?tab=contract)
  - [AirnodeRrpV0DryRun](https://sepolia-explorer.metisdevops.link/address/0x2e768206bf5112e7D7efAf1d9df614C26475193f?tab=contract)
  - [RequesterAuthorizerWithAirnode](https://sepolia-explorer.metisdevops.link/address/0xf18c105D0375E80980e4EED829a4A68A539E6178?tab=contract)

- zkEVM Cardona Testnet (Polygon zkEVM's new testnet)
  - [AccessControlRegistry](https://cardona-zkevm.polygonscan.com/address/0x7A0Ca3AEFe94d5CDe270825c15c5c38d0082139D#code)
  - [AirnodeRrpV0](https://cardona-zkevm.polygonscan.com/address/0x9499A917cF8ca139C0E06F9728E1C6A0f7a1f5F2#code)
  - [AirnodeRrpV0DryRun](https://cardona-zkevm.polygonscan.com/address/0xE9dd8301c02dD1be4388c5B4AA02C711B0Ea6c3B#code)
  - [RequesterAuthorizerWithAirnode](https://cardona-zkevm.polygonscan.com/address/0x3026ffd6a17BeB6C4c3211d5aBE5f2B0E98acB3e#code)

This PR cannot be merged until the newer Sepolia testnets are added in the [@api3/chains](https://github.com/api3dao/chains) package.

### CODE REVIEW

**Comment by dcroote** [comment]
I'm fine with removing these goerli chains since they're all deactivated / decommissioned (rather than just deprecated).

**Review by Ashar2shahid — APPROVED** [review]

**Review by dcroote — COMMENTED** [review]
Looks like the newly added Arbitrum Sepolia Testnet is failing verification..?

**Comment by vanshwassan** [comment]
> Looks like the newly added Arbitrum Sepolia Testnet is failing verification..?

Yeah, I noticed that running `deploy:deterministic` command didn't add the `transactionHash` and `receipt` in the json files for some reason. Not sure why, but I generated the receipt and added those fields manually.

**Review by dcroote — APPROVED** [review]
>  but I generated the receipt and added those fields manually.

Nice 👍  Not sure why the ethereum goerli and polygon testnet verifications are failing, but we know they're ok

**Pull request merged**
