### PR TITLE
Exports functions under /api directory on airnode-node package

### LINKED ISSUE #1412: Export functions under /api directory on airnode-node package
This is required by Airkeeper in order to be able to re-use the callApi() functionality and pass only required config values as parameters.

### PR DESCRIPTION
**Pull request by acenolaza**
Closes #1412

### CODE REVIEW

**Review by amarthadan — APPROVED** [review]
As far as I can tell `callApi` is the only function that is exported. Is that enough?

**Comment by acenolaza** [comment]
> As far as I can tell `callApi` is the only function that is exported. Is that enough?

That's all I'll need to call from Airkeeper but are you thinking that we should export all of the other functions just in case? I see [verifyTemplateId](https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/api/index.ts#L127) is also being exported

**Comment by amarthadan** [comment]
> > As far as I can tell `callApi` is the only function that is exported. Is that enough?
> 
> That's all I'll need to call from Airkeeper but are you thinking that we should export all of the other functions just in case? I see [verifyTemplateId](https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/api/index.ts#L127) is also being exported

I don't mind either way, just making sure we don't miss something we need. Up to you :slightly_smiling_face:

**Comment by acenolaza** [comment]
> > > As far as I can tell `callApi` is the only function that is exported. Is that enough?
> > 
> > 
> > That's all I'll need to call from Airkeeper but are you thinking that we should export all of the other functions just in case? I see [verifyTemplateId](https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/api/index.ts#L127) is also being exported
> 
> I don't mind either way, just making sure we don't miss something we need. Up to you slightly_smiling_face

Good call 👍🏻 I wouldn't want to have to publish a new package because of forgetting to export something 🤭 so I'll probably export a few more functions that might be needed. Also [these types](https://github.com/api3dao/airnode/blob/master/packages/airnode-node/src/types.ts#L303) would probably be used but they are already being exported.

**Pull request merged**
