### PR TITLE
Remove goerli and polygon mumbai deployments

### LINKED ISSUE #1988: Remove goerli deployments
2024-04-13 [was the sunset date](https://blog.ethereum.org/2023/11/30/goerli-lts-update) for Ethereum goerli, but even before then, [validators](https://grafana.observability.ethpandaops.io/dashboard/snapshot/fwALK9PEe7CLEOO81lma5bT6k7jq7Gcs?orgId=0&from=1707927490000&to=1713197890000), block explorers and providers ended support.

### PR DESCRIPTION
**Pull request by dcroote**
Closes #1988

### CODE REVIEW

**Review by Siegrift — COMMENTED** [review]
I haven't spotted any remnants of Goerli and Polygon mumbai and changes LGTM, but I see the contract verification script is failing.

**Comment by dcroote** [comment]
Yes, for that I created #1992 since it seems unrelated to the changes I made here. I'll investigate and open a PR for that then merge this.

**Comment by dcroote** [comment]
🤦  the error was because I forgot to actually remove `polygon-testnet` (I only removed `polygon-zkevm-goerli-testnet`).

**Comment by Siegrift** [comment]
> the error was because I forgot to actually remove polygon-testnet (I only removed polygon-zkevm-goerli-testnet)

I see. I only checked the code (and not filenames).

**Comment by dcroote** [comment]
Yea, my silly mistake. Mind approving then?

**Review by Siegrift — APPROVED** [review]
👍 LGTM

**Pull request merged**
