### PR TITLE
Fix check documentation latest path update loop

### PR DESCRIPTION
**Pull request by vponline**
Fixes grep partial matches with `latestVersion` and `latestVersions` in the check documentatiom job.

### CODE REVIEW

**Review by Siegrift — CHANGES_REQUESTED** [review]
This https://github.com/api3dao/ois/pull/22/files also removes the `latestBeaconVersion` thing.

**Comment by vponline** [comment]
> This https://github.com/api3dao/ois/pull/22/files also removes the latestBeaconVersion section.

Thanks, fixed

**Review by Siegrift — APPROVED** [review]
👍 LGTM

**Review by dcroote — APPROVED** [review]
Thanks!

**Pull request merged**
