### PR TITLE
Fix handling of quotation marks in secrets

### LINKED ISSUE #1510: Airnode fails at runtime if secrets are quoted
Raised internally in https://api3workspace.slack.com/archives/C02R79STBRA/p1666803628395139

### PR DESCRIPTION
**Pull request by amarthadan**
Fix #1510

### CODE REVIEW

**Comment by dcroote** [comment]
Is there any fix required for the airnode client?

**Comment by amarthadan** [comment]
> Is there any fix required for the airnode client?

Good question. Secrets there are loaded via dotenv that handles quotes correctly (I've just tested it) :slightly_smiling_face:

**Comment by dcroote** [comment]
> Good question. Secrets there are loaded via dotenv that handles quotes correctly (I've just tested it) 🙂

Nice!

**Comment by martinkolenic** [comment]
Test: Check if quotation marks in secrets cause deployment errors
Versions tested: v0.9.1 snapshots; master
Deployed to: AWS
Testnet: Görli

Test flow: Create secrets.env and wrap secret values in quotation marks, then attempt deployment
Subtests: Only wrap one of the values in quotes, vary the values quoted

Expected results: Quotation marks are ignored, deployment successful and Airnode works, fulfilling API requests.
Actual results: Matches expected results.

**Pull request merged**
