### PR TITLE
Release v0.11.0

### PR DESCRIPTION
**Pull request by amarthadan**

### CODE REVIEW

**Review by aquarat — APPROVED** [review]
LGTM 🆗

**Review by dcroote — APPROVED** [review]
LGTM as well. It may not be worth it, but there is a spurious `.swp` file at the top level of the repo that could be removed prior to release.

**Comment by amarthadan** [comment]
> LGTM as well. It may not be worth it, but there is a spurious `.swp` file at the top level of the repo that could be removed prior to release.

Thanks for noticing, I'll do that.

**Comment by amarthadan** [comment]
I've removed the `.swp` file but leaving the `.gitignore` changes for https://github.com/api3dao/airnode/pull/1725

**Pull request merged**
