### PR TITLE
Rename the withdrawal counter

### PR DESCRIPTION
**Pull request by bbenligiray**

### CODE REVIEW

**Review by Siegrift — COMMENTED** [review]
I still not understand why the variable can't start from 0

**Comment by bbenligiray** [comment]
Incrementing 0 costs more gas than incrementing 1

**Comment by Siegrift** [comment]
Wow. Do you have explanation for that? That seems very interesting :)

**Review by Siegrift — APPROVED** [review]

**Comment by bbenligiray** [comment]
https://ethereum.github.io/yellowpaper/paper.pdf
Appendix G
Gsset    20000    Paid for an SSTORE operation when the storage value is set to non-zero from zero.
Gsreset   5000    Paid for an SSTORE operation when the storage value’s zeroness remains unchanged or is set to zero.

Whoever creates the requester record also initializes the index at 1 and pays the 20,000 gas upfront. Then, all the following withdrawal requests will pay an additional 5,000 gas to increment the index (which is used for unique withdrawal IDs).

**Pull request merged**
